language: node_js
node_js:
- 8.4.0
before_script:
- npm install cross-env -D
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: 1/IAFiS6XRP3OwtKhbbDq9bQwOGOWMjeEDCktlvyHntwwYMXP5JGiTBnw9z_SgeXHC
env:
  global:
    secure: MiebSzYtxDKJY9YQpmvGL4ZDyhrn8kdFIlidV6MvMxsy566wNOFijjyot7QfavHzDHpAqZZfnwZkiVWZ2q7cz2zoW3or1fm3ByPSyYxoxqiku39h4am1QlqjboGe27PKa7YCs/vtUeZN/mehOFv678glYa7y814T7gVXCmhdY7JTOSlH7f8WYP1EYAP6X+3TK83sL2oDQk4jyG7Vn17RkfT2yQ/8Adbtm/WtogH/r4TZrnIe2rV26PZVdr1cFk4THFIhyvBZtTQFZN+iA4Aw2JPHWnEqVi0qZWEMHAP4Gh08eR5ksaiHP42gN7kNuFT5AwDTq6tyuMkxXn9Efq52dhcO8Wdm2nP1dKpwTjD3xSL/cCYmyisUWtyAfA16dLp+b+exf2v2Nz0bz3snJtA2Y9am55U28gI89PxRO++HE0G4fpfXCRCOZfzphj5FPVAH3Ef/JZ2X/OESVKir/mkFr9vvXQDXm+Z23DmVVcNkMjKH7M57MWXIJkEJPZ7u+7+HwiUd2ckOTNauK8IDzcTopqkenzjGfxspo6yWHydL8Exir1pyrOCHe9gsvx8+/xtrehJt61+/cU8JK8cAeATcj2/BRFmi7mBvaSjjAcZ3qn093+6/wf8fqdq3gLMy9K4f0F+lSNp9niH66RCBrmPAakgvYGyI5u4yQ/m2n2vgjW0=
